const PAGES = {
    HOME: '#home',
    CATALOG: '#catalogo',
    PROMOTIONS: '#promociones',
    CONTACT: '#contacto',
    PRICES: '#precios',
    CART: '#carrito'
}

const products = [
    {
        name: 'ALESSIO 2562-002',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/items/g9.jpeg',
        model: 'ALESSIO 2562-002',
        brand: 'ALESSIO',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'ALESSIO 2577-002',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ALESSIO 2577-002',
        brand: 'ALESSIO',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'ALESSIO 2667-001',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ALESSIO 2667-001',
        brand: 'ALESSIO',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'ALESSIO 2691-001 ',
        description: 'TBD',
        type: 'RECETA',
        ring: 'TANZA',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ALESSIO 2691-001',
        brand: 'ALESSIO',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'ALESSIO DARIO',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'ZILO',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ALESSIO DARIO',
        brand: 'ALESSIO',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: true
    },
    {
        name: 'FEDRA 0802-002',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA 0802-002',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA 0815-001',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA 0815-001',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA 0841-001',
        description: 'Product 2 Description',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA 0841-001',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA 1053-001',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA 1053-001',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA 1073-001',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA 1073-001',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA BIANCA',
        description: 'Product 2 Description',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'ACETATO',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA BIANCA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: true
    },
    {
        name: 'FEDRA DELFINA',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'ACETATO',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA DELFINA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: true
    },
    {
        name: 'FEDRA E 105',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA E 105',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: true
    },
    {
        name: 'FEDRA E15007',
        description: 'TBD',
        type: 'RECETA',
        ring: 'TANZA',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA E15007',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA E15019',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA E15019',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA 15020',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA 15020',
        brand: 'FEDRA' ,
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA E15030',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA E15030',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA E15031',
        description: 'TBD',
        type: 'RECETA',
        ring: 'TANZA',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA E15031',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA E15037',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA E15037',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA E15039',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA E15039',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA E15040',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA E15040',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA E15048',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA E15048',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA LIVIA',
        description: 'Product 2 Description',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'ACETATO',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA LIVIA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA MARGOT',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'ACETATO',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA MARGOT',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: true
    },
    {
        name: 'FEDRA MARINA',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'ACETATO',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA MARINA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA SARA',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'ACETATO',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA SARA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA VALERIA',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'ACETATO',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA VALERIA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FEDRA 5411-001',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA 5411-001',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'FEDRA ANDREA',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA ANDREA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'SOL',
        isPromoted: true
    },
    {
        name: 'FEDRA ESTELA',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA ESTELA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'FEDRA JULIANA',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA JULIANA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'FEDRA LORENA',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA LORENA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'Producto 2',
        description: 'Product 2 Description',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'PLASTIC',
        colors: 'red',
        caliber: 'TBD',
        price: '323',
        strikethorughPrice: '456',
        image: 'img/banner/banner-img.png',
        model: '1549-00223',
        brand: 'Ray Van',
        isPromotion: false,
        category: 'RECETADOS',
        isPromoted: true
    },
    {
        name: 'FEDRA MAGA',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA MAGA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'FEDRA MARCIA',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA MARCIA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'FEDRA MARTINA',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA MARTINA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'FEDRA MOREZ',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA MOREZ',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'FEDRA PAULINA',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA PAULINA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'FEDRA SILVANA',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FEDRA SILVANA',
        brand: 'FEDRA',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'FRANCIONI 0003-002',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FRANCIONI 0003-002',
        brand: 'FRANCIONI',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FRANCIONI 0101-001 ',
        description: 'TBD',
        type: 'RECETA',
        ring: 'TANZA',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FRANCIONI 0101-001',
        brand: 'FRANCIONI',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FRANCIONI 0177-001',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FRANCIONI 0177-001',
        brand: 'FRANCIONI',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FRANCIONI F20018',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FRANCIONI F20018',
        brand: 'FRANCIONI',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FRANCIONI F20024',
        description: 'TBD',
        type: 'RECETA',
        ring: 'TANZA',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FRANCIONI F20024',
        brand: 'FRANCIONI',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: true
    },
    {
        name: 'FRANCIONI LF17704',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FRANCIONI LF17704',
        brand: 'FRANCIONI',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'FRANCIONI FS048',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FRANCIONI FS048',
        brand: 'FRANCIONI',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'FRANCIONI FS048',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'FRANCIONI FS048',
        brand: 'FRANCIONI',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'ROUTE 66 1549-001',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ROUTE 66 1549-001 ',
        brand: 'ROUTE 66',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'ROUTE 66 1553-001',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO ',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ROUTE 66 1553-001',
        brand: 'ROUTE 66',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'ROUTE 66 1558-001',
        description: 'TBD',
        type: 'RECETA',
        ring: 'TANZA',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ROUTE 66 1558-001',
        brand: 'ROUTE 66',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'ROUTE 66 6033-001',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ROUTE 66 6033-001',
        brand: 'ROUTE 66',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: true
    },
    {
        name: 'ROUTE 66 CLEOPATRA',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'DAMA',
        material: 'ACETATO',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ROUTE 66 6033-001',
        brand: 'ROUTE 66',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'ROUTE 66 JULIAN',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'ACETATO',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ROUTE 66 JULIAN',
        brand: 'ROUTE 66',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'ROUTE 66 R4000',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ROUTE 66 R4000',
        brand: 'ROUTE 66',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'ROUTE 66 R4010',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ROUTE 66 R4010',
        brand: 'ROUTE 66',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'ROUTE 66 6078-002',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ROUTE 66 6078-002 ',
        brand: 'ROUTE 66',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'ROUTE 66 6078-002',
        description: 'TBD',
        type: 'SOL',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'ACETATO',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'ROUTE 66 6078-002 ',
        brand: 'ROUTE 66',
        isPromotion: true,
        category: 'SOL',
        isPromoted: false
    },
    {
        name: 'SYMBOL MATIAS',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'ACETATO',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'SYMBOL 6078-002',
        brand: 'SYMBOL',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: true
    },
    {
        name: 'SYMBOL Y43',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'SYMBOL Y43',
        brand: 'SYMBOL',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'SYMBOL Y5004',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'SYMBOL Y5004',
        brand: 'SYMBOL',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    },
    {
        name: 'SYMBOL Y5009',
        description: 'TBD',
        type: 'RECETA',
        ring: 'ENTERO',
        segment: 'CABALLERO',
        material: 'METAL',
        colors: '',
        caliber: '',
        price: '500',
        strikethorughPrice: '650',
        image: 'img/banner/banner-img.png',
        model: 'SYMBOL Y5009',
        brand: 'SYMBOL',
        isPromotion: true,
        category: 'RECETADOS',
        isPromoted: false
    }    
]

const headerSection = {
    items: [
        {
            title: 'home',
            href: '#home'
        },
        {
            title: 'catalogo',
            href: '#catalogo',
            options: [
                {
                    title: 'recetados'
                },
                {
                    title: 'sol'
                }
            ]
        },
        {
            title: 'promociones',
            href: '#promociones',
        },
        {
            title: 'contacto',
            href: '#contacto',
        },
        {
            title: 'politica de precios',
            href: '#precios',
        },
        {
            title: 'carrito',
            href: '#carrito',
        }
    ]
}


const bannerSection = {
    items : products
}

const featuresSection = {
    items: [
        {
            title: 'Delivery gratuito',
            description: 'Free Shipping on all order',
            image: 'img/features/f-icon1.png'
        },
        {
            title: 'Return Policy',
            description: 'Free Shipping on all order',
            image: 'img/features/f-icon2.png'
        },
        {
            title: '24/7 Support',
            description: 'Free Shipping on all order',
            image: 'img/features/f-icon3.png'
        },
        {
            title: 'Secure Payment',
            description: 'Free Shipping on all order',
            image: 'img/features/f-icon4.png'
        }
    ]
}

const footerSection = {
    aboutUsTitle: 'ABOUT_US_ADD',
    aboutUsDescription: 'DESCRIPTION_ADD',
    corporateTitle: 'CORPORATE_TITLE_ADD',
    corporateDescription: 'CORPORATE_DESCRIPTION_ADD',
    instagramTitle: 'INSTAGRAM_TITLE_ADD',
    instagramItems: [
        {
            imageUrl: 'img/i1.jpg',
            instagramUrl: 'https://www.instagram.com/'
        },
        {
            imageUrl: 'img/i2.jpg',
            instagramUrl: 'https://www.instagram.com/'
        },
        {
            imageUrl: 'img/i3.jpg',
            instagramUrl: 'https://www.instagram.com/'
        },
        {
            imageUrl: 'img/i4.jpg',
            instagramUrl: 'https://www.instagram.com/'
        },
        {
            imageUrl: 'img/i5.jpg',
            instagramUrl: 'https://www.instagram.com/'
        },
        {
            imageUrl: 'img/i6.jpg',
            instagramUrl: 'https://www.instagram.com/'
        },
        {
            imageUrl: 'img/i7.jpg',
            instagramUrl: 'https://www.instagram.com/'
        },
        {
            imageUrl: 'img/i8.jpg',
            instagramUrl: 'https://www.instagram.com/'
        }
    ],
    letUsBeSocialTitle: 'LET_US_BE_SOCIAL_ADD',
    followUsTitle: 'FOLLOW_US_ADD',
    facebookUrl: 'https://www.google.com',
    twitterUrl: 'https://www.google.com',
    dribbleUrl: 'https://www.google.com',
    behanceUrl: 'https://www.google.com'
}


const home = {
    headerSection,
    bannerSection,
    featuresSection,
    footerSection
}

const catalog = {
    headerSection,
    footerSection
}

const contact = {
    headerSection,
    featuresSection,
    footerSection
}

const cart = {
    headerSection,
    footerSection
}

export default {
    PAGES,
    home,
    catalog,
    contact,
    cart,
    footerSection,
    products
}